# .github/workflows/publish.yml
name: Publish to NPM and JSR

on:
  release:
    types: [prereleased, released]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install
        run: bun install

      - name: Build
        run: bun run build

      - name: Publish to NPM (Stable)
        if: github.event.action == 'released'
        run: bun run publish:npm
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to NPM (Prerelease)
        if: github.event.action == 'prereleased'
        run: bun run publish:npm:beta
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to JSR (Stable)
        if: github.event.action == 'released'
        run: bun run publish:jsr

      - name: Publish to JSR (Prerelease)  
        if: github.event.action == 'prereleased'
        run: bun run publish:jsr:beta
