name: Release PR (Stable & RC)

on:
  push:
    branches:
      - main
      - dev

jobs:
  release-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: node
          target-branch: ${{ github.ref_name }}
          config-file: .release-please-config.json
          token: ${{ secrets.GITHUB_TOKEN }}